// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Infocom.TimeManager.WebAccess.Controllers {
    public partial class TimeRegistrationController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public TimeRegistrationController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected TimeRegistrationController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Index() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult TimeSheetAddTask() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.TimeSheetAddTask);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult GetTasksForProject() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.GetTasksForProject);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult TimeSheetDeleteTask() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.TimeSheetDeleteTask);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult TimeSheetUpdateTask() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.TimeSheetUpdateTask);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public TimeRegistrationController Actions { get { return MVC.TimeRegistration; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "TimeRegistration";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string TimeSheetAddTask = "TimeSheetAddTask";
            public readonly string GetProjectForEmployee = "GetProjectForEmployee";
            public readonly string GetTasksForProject = "GetTasksForProject";
            public readonly string TimeSheetDeleteTask = "TimeSheetDeleteTask";
            public readonly string TimeSheetUpdateTask = "TimeSheetUpdateTask";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string BodyTemplate = "~/Views/TimeRegistration/BodyTemplate.ascx";
            public readonly string FooterTemplate = "~/Views/TimeRegistration/FooterTemplate.ascx";
            public readonly string HeaderTemplate = "~/Views/TimeRegistration/HeaderTemplate.ascx";
            public readonly string Index = "~/Views/TimeRegistration/Index.aspx";
            public readonly string TimeSheetTemplate = "~/Views/TimeRegistration/TimeSheetTemplate.ascx";
            static readonly _EditorTemplates s_EditorTemplates = new _EditorTemplates();
            public _EditorTemplates EditorTemplates { get { return s_EditorTemplates; } }
            public partial class _EditorTemplates{
                public readonly string TimeRegistrationEditor = "TimeRegistrationEditor";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_TimeRegistrationController: Infocom.TimeManager.WebAccess.Controllers.TimeRegistrationController {
        public T4MVC_TimeRegistrationController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index(string selectedDate) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            callInfo.RouteValueDictionary.Add("selectedDate", selectedDate);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult TimeSheetAddTask(long timeSheetID, Infocom.TimeManager.WebAccess.Models.TaskModel model, System.DateTime selectedDate, long taskID=0)
        {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.TimeSheetAddTask);
            callInfo.RouteValueDictionary.Add("timeSheetID", timeSheetID);
            callInfo.RouteValueDictionary.Add("taskID", taskID);
            callInfo.RouteValueDictionary.Add("model", model);
            callInfo.RouteValueDictionary.Add("selectedDate", selectedDate);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult GetProjectForEmployee() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetProjectForEmployee);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult GetTasksForProject(long projectID) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.GetTasksForProject);
            callInfo.RouteValueDictionary.Add("projectID", projectID);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult TimeSheetDeleteTask(long timeSheetID, long ID, System.DateTime selectedDate) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.TimeSheetDeleteTask);
            callInfo.RouteValueDictionary.Add("timeSheetID", timeSheetID);
            callInfo.RouteValueDictionary.Add("ID", ID);
            callInfo.RouteValueDictionary.Add("selectedDate", selectedDate);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult TimeSheetUpdateTask(long taskID, System.DateTime selectedDate, System.Collections.Generic.IEnumerable<System.TimeSpan> timeSpantByDays) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.TimeSheetUpdateTask);
            callInfo.RouteValueDictionary.Add("taskID", taskID);
            callInfo.RouteValueDictionary.Add("selectedDate", selectedDate);
            callInfo.RouteValueDictionary.Add("timeSpantByDays", timeSpantByDays);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
